import { SocketProvider } from "@/components/providers/socket-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CanvasMemberProvider } from "@/components/providers/canvas-member";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <CanvasMemberProvider>{children}</CanvasMemberProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
